//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazikCareService.BiztalkRepository.LISORMO01Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://birch.bupa.com/", ConfigurationName="LISORMO01Service.BizTalkLISORMO01")]
    public interface BizTalkLISORMO01 {
        
        // CODEGEN: Generating message contract since the operation GetPatientOrder is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetPatientOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderResponse GetPatientOrder(MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetPatientOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderResponse> GetPatientOrderAsync(MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Birch.HL7.Schemas.Api.GetOrderDetail")]
    public partial class GetOrderDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderIdField;
        
        private string patientIdField;
        
        private string orderStatusField;
        
        private string appointmentRecIdField;
        
        private string caseIdField;
        
        private string messageControlIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PatientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
                this.RaisePropertyChanged("PatientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("OrderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AppointmentRecId {
            get {
                return this.appointmentRecIdField;
            }
            set {
                this.appointmentRecIdField = value;
                this.RaisePropertyChanged("AppointmentRecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CaseId {
            get {
                return this.caseIdField;
            }
            set {
                this.caseIdField = value;
                this.RaisePropertyChanged("CaseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MessageControlId {
            get {
                return this.messageControlIdField;
            }
            set {
                this.messageControlIdField = value;
                this.RaisePropertyChanged("MessageControlId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatientOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Birch.HL7.Schemas.Api.GetOrderDetail", Order=0)]
        public MazikCareService.BiztalkRepository.LISORMO01Service.GetOrderDetail GetOrderDetail;
        
        public GetPatientOrderRequest() {
        }
        
        public GetPatientOrderRequest(MazikCareService.BiztalkRepository.LISORMO01Service.GetOrderDetail GetOrderDetail) {
            this.GetOrderDetail = GetOrderDetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatientOrderResponse {
        
        public GetPatientOrderResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizTalkLISORMO01Channel : MazikCareService.BiztalkRepository.LISORMO01Service.BizTalkLISORMO01, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizTalkLISORMO01Client : System.ServiceModel.ClientBase<MazikCareService.BiztalkRepository.LISORMO01Service.BizTalkLISORMO01>, MazikCareService.BiztalkRepository.LISORMO01Service.BizTalkLISORMO01 {
        
        public BizTalkLISORMO01Client() {
        }
        
        public BizTalkLISORMO01Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizTalkLISORMO01Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalkLISORMO01Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizTalkLISORMO01Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderResponse MazikCareService.BiztalkRepository.LISORMO01Service.BizTalkLISORMO01.GetPatientOrder(MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderRequest request) {
            return base.Channel.GetPatientOrder(request);
        }
        
        public void GetPatientOrder(MazikCareService.BiztalkRepository.LISORMO01Service.GetOrderDetail GetOrderDetail) {
            MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderRequest inValue = new MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderRequest();
            inValue.GetOrderDetail = GetOrderDetail;
            MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderResponse retVal = ((MazikCareService.BiztalkRepository.LISORMO01Service.BizTalkLISORMO01)(this)).GetPatientOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderResponse> MazikCareService.BiztalkRepository.LISORMO01Service.BizTalkLISORMO01.GetPatientOrderAsync(MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderRequest request) {
            return base.Channel.GetPatientOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderResponse> GetPatientOrderAsync(MazikCareService.BiztalkRepository.LISORMO01Service.GetOrderDetail GetOrderDetail) {
            MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderRequest inValue = new MazikCareService.BiztalkRepository.LISORMO01Service.GetPatientOrderRequest();
            inValue.GetOrderDetail = GetOrderDetail;
            return ((MazikCareService.BiztalkRepository.LISORMO01Service.BizTalkLISORMO01)(this)).GetPatientOrderAsync(inValue);
        }
    }
}
