//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazikCareService.BiztalkRepository.RISORMO01Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://birch.bupa.com/", ConfigurationName="RISORMO01Service.RISORMO01")]
    public interface RISORMO01 {
        
        // CODEGEN: Generating message contract since the operation GetOrder is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderResponse GetOrder(MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderResponse> GetOrderAsync(MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Birch.HL7.Schemas.Api.GetOrderDetail")]
    public partial class GetOrderDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderIdField;
        
        private string patientIdField;
        
        private string orderStatusField;
        
        private string appointmentRecIdField;
        
        private string caseIdField;
        
        private string messageControlIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PatientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
                this.RaisePropertyChanged("PatientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("OrderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AppointmentRecId {
            get {
                return this.appointmentRecIdField;
            }
            set {
                this.appointmentRecIdField = value;
                this.RaisePropertyChanged("AppointmentRecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CaseId {
            get {
                return this.caseIdField;
            }
            set {
                this.caseIdField = value;
                this.RaisePropertyChanged("CaseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MessageControlId {
            get {
                return this.messageControlIdField;
            }
            set {
                this.messageControlIdField = value;
                this.RaisePropertyChanged("MessageControlId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Birch.HL7.Schemas.Api.GetOrderDetail", Order=0)]
        public MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderDetail GetOrderDetail;
        
        public GetOrderRequest() {
        }
        
        public GetOrderRequest(MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderDetail GetOrderDetail) {
            this.GetOrderDetail = GetOrderDetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderResponse {
        
        public GetOrderResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RISORMO01Channel : MazikCareService.BiztalkRepository.RISORMO01Service.RISORMO01, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RISORMO01Client : System.ServiceModel.ClientBase<MazikCareService.BiztalkRepository.RISORMO01Service.RISORMO01>, MazikCareService.BiztalkRepository.RISORMO01Service.RISORMO01 {
        
        public RISORMO01Client() {
        }
        
        public RISORMO01Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RISORMO01Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RISORMO01Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RISORMO01Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderResponse MazikCareService.BiztalkRepository.RISORMO01Service.RISORMO01.GetOrder(MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderRequest request) {
            return base.Channel.GetOrder(request);
        }
        
        public void GetOrder(MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderDetail GetOrderDetail) {
            MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderRequest inValue = new MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderRequest();
            inValue.GetOrderDetail = GetOrderDetail;
            MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderResponse retVal = ((MazikCareService.BiztalkRepository.RISORMO01Service.RISORMO01)(this)).GetOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderResponse> MazikCareService.BiztalkRepository.RISORMO01Service.RISORMO01.GetOrderAsync(MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderRequest request) {
            return base.Channel.GetOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderResponse> GetOrderAsync(MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderDetail GetOrderDetail) {
            MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderRequest inValue = new MazikCareService.BiztalkRepository.RISORMO01Service.GetOrderRequest();
            inValue.GetOrderDetail = GetOrderDetail;
            return ((MazikCareService.BiztalkRepository.RISORMO01Service.RISORMO01)(this)).GetOrderAsync(inValue);
        }
    }
}
