//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazikCareService.BiztalkRepository.RISADTA40Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://birch.bupa.com/", ConfigurationName="RISADTA40Service.RISADTA40")]
    public interface RISADTA40 {
        
        // CODEGEN: Generating message contract since the operation MergePatientDetail is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="MergePatientDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailResponse MergePatientDetail(MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="MergePatientDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailResponse> MergePatientDetailAsync(MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BTAHL7Schemas.Api.GetPatient")]
    public partial class GetPatient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string patientIdField;
        
        private string appointmentRecIdField;
        
        private string caseIdField;
        
        private string mergePatientIdField;
        
        private string messageControlIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PatientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
                this.RaisePropertyChanged("PatientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AppointmentRecId {
            get {
                return this.appointmentRecIdField;
            }
            set {
                this.appointmentRecIdField = value;
                this.RaisePropertyChanged("AppointmentRecId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CaseId {
            get {
                return this.caseIdField;
            }
            set {
                this.caseIdField = value;
                this.RaisePropertyChanged("CaseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MergePatientId {
            get {
                return this.mergePatientIdField;
            }
            set {
                this.mergePatientIdField = value;
                this.RaisePropertyChanged("MergePatientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MessageControlId {
            get {
                return this.messageControlIdField;
            }
            set {
                this.messageControlIdField = value;
                this.RaisePropertyChanged("MessageControlId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergePatientDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BTAHL7Schemas.Api.GetPatient", Order=0)]
        public MazikCareService.BiztalkRepository.RISADTA40Service.GetPatient GetPatient;
        
        public MergePatientDetailRequest() {
        }
        
        public MergePatientDetailRequest(MazikCareService.BiztalkRepository.RISADTA40Service.GetPatient GetPatient) {
            this.GetPatient = GetPatient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergePatientDetailResponse {
        
        public MergePatientDetailResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RISADTA40Channel : MazikCareService.BiztalkRepository.RISADTA40Service.RISADTA40, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RISADTA40Client : System.ServiceModel.ClientBase<MazikCareService.BiztalkRepository.RISADTA40Service.RISADTA40>, MazikCareService.BiztalkRepository.RISADTA40Service.RISADTA40 {
        
        public RISADTA40Client() {
        }
        
        public RISADTA40Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RISADTA40Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RISADTA40Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RISADTA40Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailResponse MazikCareService.BiztalkRepository.RISADTA40Service.RISADTA40.MergePatientDetail(MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailRequest request) {
            return base.Channel.MergePatientDetail(request);
        }
        
        public void MergePatientDetail(MazikCareService.BiztalkRepository.RISADTA40Service.GetPatient GetPatient) {
            MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailRequest inValue = new MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailRequest();
            inValue.GetPatient = GetPatient;
            MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailResponse retVal = ((MazikCareService.BiztalkRepository.RISADTA40Service.RISADTA40)(this)).MergePatientDetail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailResponse> MazikCareService.BiztalkRepository.RISADTA40Service.RISADTA40.MergePatientDetailAsync(MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailRequest request) {
            return base.Channel.MergePatientDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailResponse> MergePatientDetailAsync(MazikCareService.BiztalkRepository.RISADTA40Service.GetPatient GetPatient) {
            MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailRequest inValue = new MazikCareService.BiztalkRepository.RISADTA40Service.MergePatientDetailRequest();
            inValue.GetPatient = GetPatient;
            return ((MazikCareService.BiztalkRepository.RISADTA40Service.RISADTA40)(this)).MergePatientDetailAsync(inValue);
        }
    }
}
